# Generated by Django 2.2.18 on 2021-02-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_db_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB_home',
            new_name='DB_home_href',
        ),
    ]
